function gui = initialize_gui(q0, q, dq, ddq, u)
% Creates a graphical user interface to animate an episode of the 7 link 
% biped walking. The controller can be automated or manual.
%
% Inputs:
%  ~ q0: a vector of previous joint angles
%  ~ q: a vector of joint angles
%  ~ dq: a vector of joint 
% Outputs:
%  ~ gui: a MATLAB UI for an episode of the biped
%
% author:  Kyle Naddeo
% created: 1/28/2022

%% Initialize Plot
gui.fig = figure;
set(gcf, 'units','normalized','outerposition',[0 0 1 1])  
axis equal
axis off
hold on

%% Add Table
table_left   = 0.6;
table_bottom = 0.6;
table_width  = 0.34;
table_height = 0.2175;
locations = [ "1) Free Thigh", "2) Between Thighs", "3) Free Shank", "4) Back Shank", "5) Free Foot", "6) Stance Foot", "7) HAT"]';
ue = [u(1:5); 0; u(6)];
table_data = table(q0, q, dq, ddq, ue);
vars = {'q0','q', 'dq', 'ddq', 'u'};
gui.config_table = uitable(gui.fig, 'Data', table2cell(table_data),... 
                        'RowName', locations, 'ColumnName', vars,...
                        'Units','Normalized', 'Position', [table_left table_bottom table_width table_height]);
table_extent = get(gui.config_table,'Extent');
set(gui.config_table,'Position',[table_left table_bottom table_extent(3) table_extent(4)])

%% Apply Torque Button
pb_left   = 0.67;
pb_bottom = 0.09;
pb_width  = 0.2;
pb_height = 0.1;
gui.push_button = uicontrol('style','push',...
                 'units','normalized',...
                 'position',[pb_left pb_bottom pb_width pb_height],...
                 'fontsize',14,...
                 'string','Apply Torque',...
                 'callback',{@apply_torque, gui});

%% Sliders
slider_left   = 0.65;
slider_bottom = 0.49;
slider_height = 0.05;
slider_width  = 0.25;

min_val = -100;
max_val =  100;

% U2 Slider
gui.slider_u2 = uicontrol('style','slider',...
                         'units','normalized',...
                         'position',[slider_left slider_bottom slider_width slider_height],...
                         'fontsize',14,...
                         'BackgroundColor', 'w', ...
                         'Value',u(1), ...
                         'Min', min_val,'Max', max_val,...
                         'callback', {@getSliderValues, gui});    
set(gui.slider_u2, 'Units', 'normalized')

% U3 Slider
gui.slider_u3 = uicontrol('style','slider',...
                         'units','normalized',...
                         'position',[slider_left slider_bottom-slider_height slider_width slider_height],...
                         'fontsize',14,...
                         'BackgroundColor', 'w', ...
                         'Value',u(2), ...
                         'Min', min_val,'Max', max_val,...
                         'callback', {@getSliderValues, gui});    
set(gui.slider_u3, 'Units', 'normalized')

% U4 Slider
gui.slider_u4 = uicontrol('style','slider',...
                         'units','normalized',...
                         'position',[slider_left slider_bottom-2*slider_height slider_width slider_height],...
                         'fontsize',14,...
                         'BackgroundColor', 'w', ...
                         'Value',u(3), ...
                         'Min', min_val,'Max', max_val,...
                         'callback', {@getSliderValues, gui});    
set(gui.slider_u4, 'Units', 'normalized')

% U5 Slider
gui.slider_u5 = uicontrol('style','slider',...
                         'units','normalized',...
                         'position',[slider_left slider_bottom-3*slider_height slider_width slider_height],...
                         'fontsize',14,...
                         'BackgroundColor', 'w', ...
                         'Value',u(4), ...
                         'Min', min_val,'Max', max_val,...
                         'callback', {@getSliderValues, gui});    
set(gui.slider_u5, 'Units', 'normalized')

% U6 Slider
gui.slider_u6 = uicontrol('style','slider',...
                         'units','normalized',...
                         'position',[slider_left slider_bottom-4*slider_height slider_width slider_height],...
                         'fontsize',14,...
                         'BackgroundColor', 'w', ...
                         'Value',u(5), ...
                         'Min', min_val,'Max', max_val,...
                         'callback', {@getSliderValues, gui});    
set(gui.slider_u6, 'Units', 'normalized')

% U2 Slider
gui.slider_u7 = uicontrol('style','slider',...
                         'units','normalized',...
                         'position',[slider_left slider_bottom-5*slider_height slider_width slider_height],...
                         'fontsize',14,...
                         'BackgroundColor', 'w', ...
                         'Value',u(6), ...
                         'Min', min_val,'Max', max_val,...
                         'callback', {@getSliderValues, gui});    
set(gui.slider_u7, 'Units', 'normalized')

end
